config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :orders, only: %i[create new show]

  post 'orders' => 'orders#create'
  delete 'orders/:id' => 'orders#destroy'

  devise_for :users

  namespace :admin do
    resources :orders do
      member do
        get :orders
      end
    end
    resources :devices do
      member do
        get   :purge_image
        patch :update_status
        post  :order
      end
      collection do
        delete 'destroy_multiple'
      end
    end
  end

  root 'devices#index'
  get 'index', to: 'devices#index'

  # That's for the future

  # post 'orders/:id/add' => "orders#add_quantity", as: "order_item_add"
  # post 'orders/:id/reduce' => "orders#reduce_quantity", as: "order_item_reduce"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :device

  validates :quantity, presence: true, length: { maximum: 1_000_000 }
  validates :phone_number, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 5, maximum: 100 }
  validates :delivery, presence: true
  validates :full_name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 1, maximum: 100 }
  validates :date_of_booking, presence: true

  # def total_price
  #   order.quantity * order.device.price
  # end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: %i[show]

  def show; end

  def index
    @order = Order.paginate(page: params[:page], per_page: 10)
  end

  def new
    @order = Order.new
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :phone_number)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_device, only: %i[create]
  skip_before_action :verify_authenticity_token

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(device: @device)
    if @order.save
      OrderMailer.with(order: @order).new_order_email.deliver_later
      flash[:success] = "Thank you for your booking! We'll get contact you soon!"
      redirect_to devices_path
    else
      flash[:error] = @order.errors
      render 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
    @order = @order.device
  end

  private

  # def order_params
  #   params.require(:order).permit(:name, :email, :address, :phone_number)
  # end

  def set_device
    @device = Device.find(params[:device_id])
  end

  def device_params
    params.require(:device).permit(:name, :equipment, :description, :price, :image)
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/admin/orders/index.html.erb
<h1 class="text-center mt-4">[Admin] Booking orders list</h1>
<% if (@orders) %>
    <% if (@orders.empty?) %> 
     <h5 class="text-center">No orders found</h5>
    <% else %>
    <div class="text-center flickr_pagination">
      <%= will_paginate @order, :container => false %>
    </div>    
      <table class="table table-sm table-dark">
        <thead>
          <tr>
            <th scope="col">Number of order</th>
            <th scope="col">Customer Email</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Total price</th>
            <th scope="col">Delivery method</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>            
              <td><%= order.id %></td>
              <td><%= order.email %></td>
              <td><%= truncate(order.description, length: 500) %></td>
              <td><%= truncate(order.equipment, length: 500)  %></td>
              <td><%= order.price %></td>
              <td><%= link_to 'Details', admin_order_url(order), class: "btn btn-outline-primary" %></td>    
          </tr>
        </tbody>
      </table>
        <% end %>
        </tbody>
      </table>    
  <% end %>
<% end %>

app/views/admin/orders/show.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th {
  padding: 5px;
   width: 100px;
  text-align: right;
}

td {
  padding: 5px;
   width: 500px;
  text-align: left;
}
</style>

<h1 class="text-center mt-4">[ADMIN] Order details: № <%= @order.id %> </h1>

<div class="container">
<table style="width:100%">
    <tr>
        <th scope="row">Customer Email</th>
        <td><%= @order.email %></td>
    </tr>
    <tr>
        <th scope="row">Customer Name</th>
        <td><%= @order.full_name %></td>
    </tr>
    <tr>
        <th scope="row">Phone number</th>
        <td><%= @order.phone_number %></td>
    </tr>
    <tr>
        <th scope="row">Device</th>
        <td><%= @order.device %></td>
    </tr>

    <tr>
        <th scope="row">Start date of booking</th>
        <td><%= @order.date_of_booking %></td>
    </tr>
    <tr>
        <th scope="row">Term of booking</th>
        <td><%= @order.quantity %></td>
    </tr>
    <tr>
        <th scope="row">Delivery method</th>
        <td><%= @order.delivery %></td>
    </tr>
</table>
</div>