config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :orders, only: %i[create new show]

  post 'orders' => 'orders#create'
  delete 'orders/:id' => 'orders#destroy'

  devise_for :users

  namespace :admin do
    resources :orders do
      member do
        get :orders
      end
    end
    resources :devices do
      member do
        get   :purge_image
        patch :update_status
        post  :order
      end
      collection do
        delete 'destroy_multiple'
      end
    end
  end

  root 'devices#index'
  get 'index', to: 'devices#index'

  # That's for the future

  # post 'orders/:id/add' => "orders#add_quantity", as: "order_item_add"
  # post 'orders/:id/reduce' => "orders#reduce_quantity", as: "order_item_reduce"
end

app/models/device.rb
class Device < ApplicationRecord
  has_one_attached :image
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :equipment, presence: true, length: { minimum: 2, maximum: 500 }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than: BigDecimal(10**7) }
  validates :image, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'], size_range: 1..10.megabytes }

  enum :status, %i[actual deleted]

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
  end
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < Admin::BaseController
  before_action :set_device, only: %i[show edit update destroy purge_image update_status]

  def show; end

  def new
    @device = Device.new
  end

  def index
    @device = Device.paginate(page: params[:page], per_page: 10)
    @devices = if params[:search]
                 Device.search(params[:search]).order('created_at DESC')
               else
                 Device.all.order('created_at DESC')
               end
  end

  def update_status
    params[:status].present? && Device.statuses.keys.include?(params[:status].to_sym)
    @device.update(status: params[:status])
    redirect_to admin_device_url(@device), notice: "Status updated to #{@device.status}"
  end

  def create
    @device = Device.new(device_params)
    if @device.valid?
      @device.save
      flash[:success] = 'Console was created successfully'
      redirect_to admin_devices_path
    else
      flash[:error] = @device.errors
      render 'edit'
    end
  end

  def update
    if @device.update(device_params)
      flash[:notice] = 'Console was updated successfully.'
      redirect_to admin_device_url(@device)
    else
      render 'edit'
    end
  end

  def edit; end

  def purge_image
    @device.image.purge
    redirect_back fallback_location: admin_devices_path, notice: 'Success'
  end

  def destroy_multiple
    Device.destroy(params[:device_ids])
    respond_to do |format|
      format.html { redirect_to admin_devices_url }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge_later
    redirect_back(fallback_location: admin_devices_path)
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :equipment, :description, :price, :image)
  end

  def image
    ActiveStorage::Attached::One.new('image', Device.find(id), dependent: :purge_later)
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  skip_before_action :authenticate_user!, only: 'reply', raise: false

  def show
    @device = Device.find(params[:id])
  end

  def index
    redirect_to admin_devices_path if current_user
    @device = Device.actual.paginate(page: params[:page], per_page: 10)
    @devices = if params[:search]
                 Device.actual.search(params[:search]).order('created_at DESC')
               else
                 Device.actual.order('created_at DESC')
               end
  end
end

app/views/admin/devices/_console.html.erb
<div class="container">
  <% @device.each do |device| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">          
          <div class="card-body">
            <h5 class="card-title"><%= link_to device.name, admin_device_url(device), class: "text-success" %></h5>
              <div class="form-group row">

               <div class="field">
                <% if device.image.attached? %>
                <%= image_tag (device.image), style: "width: 500px" %>  
                <% else %>
                <%= image_tag("default_image.jpg", :size => "360x280", :crop => :fill) %>
                <% end %>       
              </div>  
                <p class="card-text"><%= truncate(device.description, length: 500) %></p>
                <li class="card-title">Equipment: <%= truncate(device.equipment, length: 500) %></li>
                <li class="card-title">Price for 1 day: <%= device.price %> $</li>
        
                <%= link_to 'View details', admin_device_url(device), class: "btn btn-outline-success" %>                
                <%= link_to 'Edit', edit_admin_device_path(device), class: "btn btn-outline-info" %>               
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/devices/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @device %>
      <%= form_with(model: [:admin, @device], class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>

        <div class="form-group mb-3">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of console" %>
          </div>
        </div>

        <div class="form-group mb-3">
          <% f.label :status, style: "display: block" %>
          <% f.select :status, ["Actual", "Deleted"] %>       
        </div>

        <div class="form-group mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 5, class: "form-control shadow rounded", placeholder: "Description of console" %>
          </div>
        </div>

        <div class="form-group mb-3">
          <%= f.label :equipment, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :equipment, rows: 5, class: "form-control shadow rounded", placeholder: "Equipment of console" %>
          </div>
        </div>

        <div class="form-group mb-3">
          <%= f.label :price, style: "display: block" %>
          <%= f.text_field :price, class: 'form-control form-control-lg', placeholder: "Price per day, $" %>          
        </div>

       <div class="form-group mb-3">
       <%= f.label :image, class: "col-2 col-form-label text-light" %>    
              <% if @device.image.attached? %>
                <%= image_tag @device.image, style: "width: 500px; display: block" %>  
                <%= link_to "Delete image", purge_image_admin_device_path(@device), method: :delete %>         
               <% end %>                                
          <%= f.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group row justify-content-center"> 
          <%= f.submit "Submit", :class => 'btn btn-outline-light btn-lg' %>    
          <%= link_to "Cancel", admin_devices_path, data: { confirm: 'Are you sure?' } %>           
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/devices/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit console</h1>
  <%= render 'form' %>
</div> 

app/views/admin/devices/index.html.erb
<h1 class="text-center mt-4">[ADMIN] Listing all consoles</h1>
<% if (@devices) %>
    <% if (@devices.empty?) %> 
     <h5 class="text-center">No devices found</h5>
    <% else %>
    <div class="text-center flickr_pagination">
      <%= will_paginate @device, :container => false %>
    </div>
    <%= form_tag destroy_multiple_admin_devices_path, method: :delete do %>
      <table class="footable table table-bordered toggle-arrow-tiny" data-page-size="31" >
        <thead>
        <tr>
          <th><center>Status</center></th>
          <th><center>Image</center></th>
          <th><center>Name</center></th>
          <th><center>Description</center></th>
          <th><center>Equipment</center></th>
          <th><center>Price for 1 day, $</center></th>
          <th><center>Action</center></th>
          <th data-sort-ignore="true"><input type="checkbox" id="selectAll"></input> <%= submit_tag "Delete selected", :class => 'btn btn-primary btn-xs' %></th>
        </tr>
        </thead>
        <tbody>
        <% @devices.each do |device| %>
          <tr>
            <td><%= device.status %></td>
            <td><% if device.image.attached? %>
                <%= image_tag (device.image), style: "width: 300px" %>  
                <% else %>
                <%= image_tag("default_image.jpg", :size => "360x280", :crop => :fill) %>
                <% end %>  </td>
            <td><%= device.name %></td>
            <td><%= truncate(device.description, length: 500) %></td>
            <td><%= truncate(device.equipment, length: 500)  %></td>
            <td><%= device.price %></td>
            <td><%= link_to 'View details', admin_device_url(device), class: "btn btn-outline-success" %>                
                <%= link_to 'Edit', edit_admin_device_path(device), class: "btn btn-outline-info" %>   </td>
            <td><%= check_box_tag "device_ids[]", device.id, false, class: 'selectable' %></td>
          </tr>
        <% end %>
        </tbody>
        <tfoot>
        </tfoot>
      </table>
    <% end %>
  <% end %>
<% end %>

app/views/admin/devices/new.html.erb
<h1 class="text-center mt-4">Create new console</h1>
<%= render 'form' %>

app/views/admin/devices/show.html.erb
<h1 class="text-center mt-4">Showing device details</h1>
<h2 class="text-center mt-4"><%= @device.name %></h2>
  <% if @device.status == 'deleted' %>
      <div class="card-text text-center"><b><h4>Status: <%= @device.status %></h4></b></div>
  <% end %> 
    <div class="card-text text-center">
        <%= button_to "Delete",
              update_status_admin_device_path(@device, status: 'deleted'),
              method: :patch, 
              form: { data: { confirm: "Are you sure you want to delete the product?" } },
              class: "btn btn-danger" %>
    </div>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
        </div>
        <div class="card-body">     
                <% if @device.image.attached? %>
                <%= image_tag (@device.image), style: "width: 500px" %>  
                <% else %>
                <%= image_tag("default_image.jpg", :size => "360x280", :crop => :fill) %>
                <% end %>   
                <div class="card-text text-center"><b><h4>Description: </h4></b><%= @device.description %></div>
                <div class="card-text text-center"><b><h4>Equipment: </h4></b><%= @device.equipment %></div>
                <div class="card-text text-center"><b><h4>Price for 1 day: </h4></b><%= @device.price %> $</div>
          <%= link_to "Edit", edit_admin_device_path(@device), class: "btn btn-outline-info" %>               
        </div>
      </div>
    </div>
  </div>
</div>