config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :orders, only: %i[create new show]

  post 'orders' => 'orders#create'
  delete 'orders/:id' => 'orders#destroy'

  devise_for :users

  namespace :admin do
    resources :orders do
      member do
        get :orders
      end
    end
    resources :devices do
      member do
        get   :purge_image
        patch :update_status
        post  :order
      end
      collection do
        delete 'destroy_multiple'
      end
    end
  end

  root 'devices#index'
  get 'index', to: 'devices#index'

  # That's for the future

  # post 'orders/:id/add' => "orders#add_quantity", as: "order_item_add"
  # post 'orders/:id/reduce' => "orders#reduce_quantity", as: "order_item_reduce"
end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SPIELKONSOLEN", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">       
       <% if current_user %>
            <li><%= link_to "Create", new_admin_device_url %></li>
            <li><%= link_to "Orders", admin_orders_url %></li>
            <li>Your Profile (admin): <%= current_user.email %></li>
            <ul class="nav navbar-nav navbar-right">
              <%= form_tag(admin_devices_path, :method => "get", id: "search-form-for") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
                <%= submit_tag "Search" %>
              <% end %>
            </ul>
            <% else %>          
            <ul class="nav navbar-nav navbar-right">
              <%= form_tag(devices_path, :method => "get", id: "search-form-for") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
                <%= submit_tag "Search" %>
            <% end %>
            </ul>
          <% end %> 
        
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>          
        <% end %>
      </ul>     
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spielkonsolen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'custom_js' %>  
  </head>
  
 <body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>